cc_library(
    name = "ModelTest",
    srcs = [],
    hdrs = ["modelTest.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = ["//src/fastMatrix:FastMatrix", "//src/model:Model"]
)