cc_library(
    name = "Model",
    srcs = ["layer.cpp", "model.cpp", "trainingData.cpp"],
    hdrs = ["layer.h", "model.h", "trainingData.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = ["//src/fastMatrix:FastMatrix"],
)